### PR TITLE
Adds user related variables to signature (Closes #146)

### LINKED ISSUE #146: User first name in signature
Hello,

Is there a way to add a varaible for user firstname in the signature?

### PR DESCRIPTION
**Pull request by taoeffect**
You can now use the following variables in your signature:

```
{%user.fullName%}
{%user.firstName%}
{%user.lastName%}
```

Would be awesome if this could be merged and released ASAP because Help Scout is killing our account after their bait & switch and we'd like to move to FreeScout!

Thanks for making this amazing free alternative!

### CODE REVIEW

**Comment by freescout-helpdesk** [comment]
$this->user contains a user to whom conversation is assigned. $this->created_by_user contains a user who created the thread. So $this->created_by_user should be used. We will fix this.

**Comment by taoeffect** [comment]
> $this->user contains a user to whom conversation is assigned. $thread->created_by_user contains a user who created the thread.

I'm confused, isn't it supposed to be the user to whom the conversation is assigned? I.e. the person replying? That's how it is on Help Scout...

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/commit/471920a0babe1d46fefa3ac288acabbbd6830673

**Comment by taoeffect** [comment]
Thanks! I just verified that it works in the latest release. 😄

**Pull request merged**
