### PR TITLE
Add "Followers" folder

### PR DESCRIPTION
**Pull request by avenjamin**
Add "Followers" folder to show followed conversations.

### CODE REVIEW

**Comment by freescout-helpdesk** [comment]
Thanks, but not needed in the core. Can be added via a custom module.

**Comment by avenjamin** [comment]
I disagree.

In the Core you have the ability to star a conversation and there is a Starred folder.
You have the ability to follow and unfollow a conversation so why no Following folder?

I get that you have a Followers Module already, but that only adds additional functionality to add other followers.

Currently to see conversations you're following you have to go to the Search menu in the top right, then click "Conversations I'm following" which takes you to a different layout, then to go back to the folders you have to use the back button in the browser.

This makes the Core Follow/Unfollow feature more accessible and keeps you in the same layout/view as the other folders.

Please reconsider.

Thanks

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Development-Process

**Comment by avenjamin** [comment]
Would you consider adding this to the Followers module?

I don't currently have a license for it so I can't contribute directly, but if you really don't think this belongs in core then the Followers module would make the most sense.

**Pull request closed without merging**
