### PR TITLE
Custom conversation type

### PR DESCRIPTION
**Pull request by Lars-**
This PR adds a custom conversation type that can be used in modules. 
I'm currently working on a module that will be open source that needs these changes.

### CODE REVIEW

**Comment by freescout-helpdesk** [comment]
Can you please submit it in one commit and without messing up white spaces.

**Comment by Lars-** [comment]
Where did I mess up the whitespaces? I explicitly checked for that. I even added 3 more commits to fix whitespace mistakes. 

I will change it into one commit when I know what is wrong with the white spaces.

**Comment by freescout-helpdesk** [comment]
We don't need these commits in this pull request:

**Comment by Lars-** [comment]
I changed it to one commit (and one merge from master).

**Comment by freescout-helpdesk** [comment]
Much better now. Just it would be good not to add a space after `!` in the future:

**Pull request merged**
