### PR TITLE
fix issue for HTML purifier

### PR DESCRIPTION
**Pull request by smilemittal**
I have ignored "mso" comments in HTML, So it did not hide links or any other content in the commented block.
Also, I have whitelist style for HTML, So HTML content render properly.

### CODE REVIEW

**Comment by freescout-helpdesk** [comment]
It would be good to get some description. Some of these changes we can't accept.

**Comment by smilemittal** [comment]
I have update the description above

**Comment by freescout-helpdesk** [comment]
Can you provide examples.

**Comment by smilemittal** [comment]
`<a href="https://www.maklerinfo.biz/maklerportal/?show=kunde&kunde=5002970262&Job_archiveintrag=b50365561a57c1fc97fc">to the document</a><! --<![endif]-->
        `
        
In the code above, a link button goes missing because it gets removed during the filtering process.

**Comment by freescout-helpdesk** [comment]
> I have ignored "mso" comments in HTML, So it did not hide links or any other content in the commented block.

https://github.com/freescout-helpdesk/freescout/commit/0826102f6e97d918dd5091fd4a0bbf4679870e76

Your purifier config still does not enable `<v:roundrect>` elements. And we don't see any solutions to allow it for now.

**Comment by freescout-helpdesk** [comment]
> with the purifier I just enabled style tag and CSS class

Unfortunately it's no use as HTML Purifier library removed `<v:roundrect>` element.

**Pull request closed without merging**
