### PR TITLE
Conversations bulk actions

### PR DESCRIPTION
**Pull request by Junker**

### CODE REVIEW

**Comment by freescout-helpdesk** [comment]
Thanks. Will check it soon.
Can you use main ajax() method in ConversationsController for ajax actions instead of ajaxBulk().

**Comment by Junker** [comment]
IMHO keep all ajax requests in one function is wrong, this one function will grow and grow. 
I think need to make refactoring, and add separated route for every action.

**Comment by freescout-helpdesk** [comment]
No worries. Modular architechture will not allow it to grow too much.

**Comment by freescout-helpdesk** [comment]
When using search:

> Undefined variable: mailbox (View: /resources/views/conversations/partials/bulk_actions.blade.php)

**Comment by freescout-helpdesk** [comment]
Will fix it.

**Pull request merged**
