### PR TITLE
Bounce detection improvement

### PR DESCRIPTION
**Pull request by guestisp**
Small improvement to bounce detection. Quick & Dirty fix to detect AWS bounces and Exim bounces

### CODE REVIEW

**Comment by freescout-helpdesk** [comment]
Conversation will be created always, it allows support agents understand that their email to customer has not been delivered.

Bounce detection is used to avoid sending auto replies, to avoid infinite loops: https://github.com/freescout-helpdesk/freescout/blob/master/app/Listeners/SendAutoReply.php#L34

**Comment by guestisp** [comment]
Uhm, maybe we can move all bouces to a dedicated folder (something like the Spam folder) ?

This to avoid mixing customers requests from bounces. We have some transactional mail sent with a freescout mailbox (we are not sending these email via freescout, only the From is set to a freescout mailbox). All bounces are triggering a new conversation but in this case there is no need for a conversation, or at least, there is no need to flood the mailbox primary folder with bounces.

A dedicated folder and an autoreply block would be ok.

**Comment by freescout-helpdesk** [comment]
> maybe we can move all bouces to a dedicated folder (something like the Spam folder)

Not in the core.

**Comment by guestisp** [comment]
> Not in the core.

Why not ? Users can't automate the move. Why not adding a configurable option asking how to manage a bounce? Maybe: "Silenty delete them", "Move them to bounce folder", "Do nothing"

**Comment by freescout-helpdesk** [comment]
You can create a feature request here https://freescout.net/request-feature/ to see if anybody needs it.
For now feel free to implement it as a custom module.

**Comment by guestisp** [comment]
Any guide on modules development?

**Comment by freescout-helpdesk** [comment]
See existing modules and:

- https://nwidart.com/laravel-modules/v2/introduction
- https://github.com/tormjens/eventy

**Comment by guestisp** [comment]
Let me check, but I think a new filter should be called on bounce receipt. By using a custom module to just skip conversation in case of bounce seems a little bit overkill to me. Tons of code (mostly for module scheleton) when just 2 line of code are needed (a simple IF)

**Comment by guestisp** [comment]
I've created a module for bounce management. There is only one missing thing that I don't know how to fix: I need to skip the `$this->saveCustomerThread` and `$this->saveUserThread` in `FetchEmails`

I've thought to create a filter, a sort of `preHook`. Do you have any suggestion on it's name ?

**Comment by freescout-helpdesk** [comment]
> I've thought to create a filter, a sort of preHook. Do you have any suggestion on it's name ?

Something like `fetch_emails.should_save_thread`

**Pull request merged**
