### PR TITLE
Css changes mainly for the responsiveness and usability of the dashboard

### PR DESCRIPTION
**Pull request by nickbe**
One additional comment: the small top line above the menu was inserted to make icons clickable on iOS and iPads and iPhones X onward, because there's some space needed on top.

### CODE REVIEW

**Comment by fvdm** [comment]
You used the wrong branch (dist). Better close this PR and redo the changes on `master` branch. You find the branch menu in the top-left corner when viewing the file.

image

**Comment by freescout-helpdesk** [comment]
Some ideas from the PR have been adopted, others - declined.

In the future updates will be accepted only one-by-one like this:

- Adjust logo brightness on hover https://github.com/freescout-helpdesk/freescout/commit/cc5526f7f3974f1199e52b52ac732714bde84630
- Condense dashboard content https://github.com/freescout-helpdesk/freescout/commit/9b64cc270aeac87045bab2e74c7f9e3d2cc98684
- Adjust transparent button color https://github.com/freescout-helpdesk/freescout/commit/6cffdba578f047e2cd11a73afd0d5bf965b61adb
- Hightlight new Unassigned and Mine conversations in the dashboard https://github.com/freescout-helpdesk/freescout/commit/608e6e7a1d3b25bff6181073ca24ef3db192f9c9

**Comment by nickbe** [comment]
Lots of new changes have made to the dashboard layout since then. 
If you need all then changes to be seperated then I can try, but I'm not sure if I'm able to distinguish everything because a lot of try and error was involved.

**Comment by nickbe** [comment]
Ok - I've made several new pull requests from path-2 up a couple of minutes ago. I've tried to seperate things which could be easily distinguished.

I hope the changes are well enough documented, and I hope that I didn't forget anything when committing and seperating the changes.

In upcoming changes it'll be easier because the issues are all better seperatable.
Please let me know if it's ok this way.

**Pull request closed without merging**
