### PR TITLE
delete some comment. because it contain customer name.

### PR DESCRIPTION
**Pull request by totake0224**
Please delete some comment from source code.

### CODE REVIEW

**Comment by freescout-helpdesk** [comment]
You are making too serious changes in a critical function.
Send us examples of subject and filename. We'll fix it ourselves.

**Comment by totake0224** [comment]
Hello.
this pull request only delete some comment that contain customer name.

**Comment by freescout-helpdesk** [comment]
Not only: https://github.com/freescout-helpdesk/freescout/pull/3184/commits/786bd3bde395b1c8fcb6e2b919ca8698ea1de3aa

**Comment by totake0224** [comment]
sorry I mistakenly push something wrong source code.

**Pull request closed without merging**
