### PR TITLE
make mail receive time configurable

### PR DESCRIPTION
**Pull request by totake0224**
this change will make configurable mail receive time.
option 1: Mail fetch time as receive time (current, default)
option 2: Mail server receive time as receive time (added)
under option 2 user could know actual mail receive time after system down or fetching trouble.

setting data will be saved in .env file

### CODE REVIEW

**Comment by freescout-helpdesk** [comment]
Few things to adjust:

1) Rename the parameter all over the code and use boolean as a value.
```
'server_time_as_received'    => env('APP_SERVER_TIME_AS_RECEIVED', '0'),
```
change to:
```
'use_mail_date_on_fetching'    => env('APP_USE_MAIL_DATE_ON_FETCHING', false),
```

2) Move option to "Manage > Mail Settings > Fetching Emails" section (after "Fetching Interval").

3) Change "Mail Timestamp" to "Mail Date & Time" and change "Set server time as received" to "Use date from mail header on fetching".

4) Add spaces.
```
if($server_time_as_received){
```
change to:
```
if ($server_time_as_received) {
```

**Comment by totake0224** [comment]
Thank you. I will adjust and resend another pull request

**Comment by totake0224** [comment]
change parameter name and setting place.
and fix wrong timezone problem.

**Comment by freescout-helpdesk** [comment]
We've added it as a single commit: https://github.com/freescout-helpdesk/freescout/commit/196e484448712cf836fe667c9aed783befd0c9b0

**Pull request closed without merging**
