### PR TITLE
Fixes #961: Read only import, import date, hash dupes, message_id on send

### PR DESCRIPTION
**Pull request by dsukhin**
Addressing #691

### CODE REVIEW

**Comment by dsukhin** [comment]
Tested:
[x] no more dupe imports with missing message id
[x] date created is set to date of email, if missing, $now
[x] read only UI
[] read only works
[] last reply and updated dates also set to email date on create (REQUESTING HELP)

**Comment by freescout-helpdesk** [comment]
Please submit PR into master branch.

**Comment by dsukhin** [comment]
Will rebase these changes, standby please

**Comment by freescout-helpdesk** [comment]
Please create a new PR without got messed up a bit.

**Pull request closed without merging**
