### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by admdly**
I have updated dependencies where extremely safe to do so as per #1355. To help with review, I have broadly separated my commits into security, php8, and general to help with review. 

From manually reviewing these changes, I don't believe they introduce any issues. However, if there are any issues please tag me and I will resolve them personally.

### CODE REVIEW

**Comment by freescout-helpdesk** [comment]
Notice that some vendor files have been overridden: https://github.com/freescout-helpdesk/freescout/blob/dist/composer.json#L112

**Comment by admdly** [comment]
I made no such changes - perhaps this was related to a dependency update? - as far as I can see there have been no significant/breaking changes.

**Comment by freescout-helpdesk** [comment]
What overriding is: https://blog.shahednasser.com/how-to-override-classes-in-php-and-composer/

Some vendor files are overridden: https://github.com/freescout-helpdesk/freescout/tree/dist/overrides
Their corresponding packages' version should be preserved or those files should be manually re-overridden.

**Comment by admdly** [comment]
My mistake, I couldn't see what you were referring to on mobile. Is there any reason for the overrides other than patching outdated versions with fixes? That is, can these be removed assuming the underlying package is now fixed?

**Comment by freescout-helpdesk** [comment]
Unfortunately, not. Updates are complex.

**Comment by admdly** [comment]
I’ll take a look into each of these for the updated packages and fix as appropriate. Some overrides no longer seem needed, but if they are I will ensure the override is updated to apply to the updated package.

**Comment by admdly** [comment]
Working through the overrides, I can see some are simple one line fixes or are fixes to issues that have now been resolved upstream. Is there any reason to keep these given the maintenance burden and blocking of vendor updates? 

Surely it would be better to fix upstream or in the project itself? I will make any changes to achieve this. 

For the more substantial overrides, I will update these for the relevant packages and lock the version appropriately.

**Comment by freescout-helpdesk** [comment]
We've checked updated dependencies, new set of dependencies does not work on a shared hosting:
```
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /vendor/opis/closure/src/SerializableClosure.php on line 381
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 149
```

Thanks for your efforts. These works can be stopped.

**Comment by admdly** [comment]
This was still a WIP but sure, I’ll continue my work elsewhere.

**Pull request closed without merging**
