### PR TITLE
Encrypt mail_password

### PR DESCRIPTION
**Pull request by davask**

### CODE REVIEW

**Comment by freescout-helpdesk** [comment]
Thanks
1) Pull requests should be sent into `master` branch: https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#github-workflow
2) Already entered passwords should be converted into encrypted and continue to work.

**Comment by davask** [comment]
Hi,

OK for push on Master.
I m not sure how to handle point 2 that would require a 1 time task, task that I would prefer users to make volontary instead of automatically cause it requires modification of data and can break everything.
Any suggestion?

**Comment by freescout-helpdesk** [comment]
It can be converted without breaking anything.

**Comment by freescout-helpdesk** [comment]
It looks like something went wrong - too many commits.

**Comment by davask** [comment]
Yes, I started over, I m waiting for you to validate the other pull request before pushing that one again

**Pull request closed without merging**
