### PR TITLE
Add "fetch_emails.should_save_thread" hook

### PR DESCRIPTION
**Pull request by guestisp**
As per #184 here we add a new hook to block thread creation (needed by module developers)

### CODE REVIEW

**Comment by guestisp** [comment]
As wrote on Eventy docs, any parameter following the filter name is sent as function argument. As some module could modify the $hook value (or just returning `false` to block the conversation creation) i've used the whole $hook as second parameter

If noone is listening to this hook, the original hook value is returned otherwise new values are returned from the module (or false to block the creation)

Doing as you are suggesting, the module can only return false

**Comment by freescout-helpdesk** [comment]
`$hook` is not used in the code, so it is useless to change it via the filter. Filters mus return what they receive as a second parameter.

**Comment by guestisp** [comment]
I'm planning to use $hook today.

**Comment by freescout-helpdesk** [comment]
Just add another filter before `If`:
```
$data = \Eventy::filter('fetch_emails.data_to_save', $data);
```
`$hook` renamed into `$data`

**Comment by guestisp** [comment]
With this you are forcing to use 2 hooks when 1 should be enough

**Comment by guestisp** [comment]
Something like this ?

**Comment by guestisp** [comment]
Thank you

**Pull request merged**
