### PR TITLE
Bounce detection improvements

### PR DESCRIPTION
**Pull request by guestisp**

### CODE REVIEW

**Comment by freescout-helpdesk** [comment]
Where does this solution come from?
`Return-Path` can be set to `<>` by some mail server for a regular email too.

**Comment by guestisp** [comment]
I've never seen, in about 15 years, a single mail with return path set as <> for something different than a bounce (or spam/bulk email)

**Comment by freescout-helpdesk** [comment]
Existing bounce detection methods do not detect some of your incoming bounce emails?

**Comment by guestisp** [comment]
In some case, yes, that's why there are some additional log in this PR

**Pull request merged**
