### PR TITLE
Removing INBOX as default IMAP folder

### PR DESCRIPTION
**Pull request by rosinghal**
- Stop showing INBOX in view file for `IMAP Folders` field.
- Allow saving INBOX in DB.
- Stop fetching of INBOX folder by default.

Check https://github.com/freescout-helpdesk/freescout/issues/483 for more details.

### CODE REVIEW

**Comment by freescout-helpdesk** [comment]
Please chenge the implementation a bit: show and fetch from INBOX as before, but allow to remove the INBOX folder in mailbox's "Fetching Emails" settings.

**Comment by freescout-helpdesk** [comment]
Please submit a new pull request.

**Comment by rosinghal** [comment]
@freescout-helpdesk If I am understanding it right you are asking to revert changes in [app/Console/Commands/FetchEmails.php](https://github.com/freescout-helpdesk/freescout/pull/521/files#diff-cf387f916f7e115abce39dc25ce91403). Is this what you are asking?

**Comment by freescout-helpdesk** [comment]
IMAP Folders field should function as it works now in FreeScout 1.5.2.
You may want to allow to remove INBOX item from the list and let select another folder. At least one folder must be selected in the IMAP Folders field.

**Pull request closed without merging**
