### PR TITLE
encrypt out_password

### PR DESCRIPTION
**Pull request by davask**

### CODE REVIEW

**Comment by freescout-helpdesk** [comment]
Thanks
1) Pull requests should be sent into `master` branch: https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#github-workflow
2) See how `in_password` has been converted into encrypted form: https://github.com/freescout-helpdesk/freescout/pull/124
Just no need to change DB field type, as it already ok.

**Comment by davask** [comment]
OK for point 1

Not sure to understand what you mean by point 2

**Comment by freescout-helpdesk** [comment]
Existing passwords should be converted into encrypted, see https://github.com/freescout-helpdesk/freescout/pull/124/commits/66930b74088382a61721f54c732f350a52900b0c

**Comment by freescout-helpdesk** [comment]
Pull request is still sent to the `dist` instead of `master`

**Comment by davask** [comment]
I m starting over a lots of confusion here on the pull request (which is my first ever by the way :D)

**Pull request closed without merging**
