### PR TITLE
Added hooks in preparation for custom signatures module

### PR DESCRIPTION
**Pull request by Lars-**

### CODE REVIEW

**Comment by freescout-helpdesk** [comment]
Some adjustments needed:

1) Rename $replacedText into $replaced_text (this is the way of naming variables is used in FreeScout) https://github.com/freescout-helpdesk/freescout/pull/1748/commits/2458539c6ff955c92325842603ec0750782015ca#diff-9ca4915cc1c99dfae402adeba8bfc742f55f42364fb5bcf87732a384183f3226R1063

2) Rename `conversation.save_send_reply` into `conversation.send_reply_save`: https://github.com/freescout-helpdesk/freescout/pull/1748/commits/2458539c6ff955c92325842603ec0750782015ca#diff-d28775712f1367649ffe7b2004708dbc65e32392450707f29b38477c7fb8ff2cR743

3) Rename `mailboxes.on_save_settings` into `mailbox.settings_before_save`: https://github.com/freescout-helpdesk/freescout/pull/1748/commits/2458539c6ff955c92325842603ec0750782015ca#diff-a87fdd4b3d08e15ab3b8bb96f11b859a85d5c22b2a6ab6b071fe9121053db7fbR207

4) Rename `mailbox_update_init` into `mailbox.update_init`: https://github.com/freescout-helpdesk/freescout/pull/1748/commits/2458539c6ff955c92325842603ec0750782015ca#diff-a8a9ec936a81c0be3ec51ef3a5e965f5bc379609bd0bb389f4fe542be63207b2R446

5) Rename `conv_editor.before_status_field` into `conversation.editor_toolbar_prepend`: https://github.com/freescout-helpdesk/freescout/pull/1748/commits/2458539c6ff955c92325842603ec0750782015ca#diff-bc8de14e2cc8989678a8255a6dbede55774b347d8da5d238db14251c2b6184d2R9

6) Rename `mailboxes.view_after_settings_on_update` into `mailbox.update_after_signature`: https://github.com/freescout-helpdesk/freescout/pull/1748/commits/2458539c6ff955c92325842603ec0750782015ca#diff-a213aec91f33552ee4de61df60c113944770752c342eab0d86cc957186ef2c25R172

**Comment by Lars-** [comment]
Done!

**Comment by Lars-** [comment]
The module is already working and finished, so it can be added to the community modules.
[https://github.com/LJPc-solutions/freescout-alternative-signatures-module](https://github.com/LJPc-solutions/freescout-alternative-signatures-module )

**Comment by freescout-helpdesk** [comment]
Great. We'll add it after hooks will be released.

**Pull request merged**
