### PR TITLE
Added hooks for custom fetch email providers

### PR DESCRIPTION
**Pull request by Wouter0100**
This allows us to create custom importers for e-mail. It will use the FetchEmails class to add the e-mails by "simulating" the Message and Attachment classes. An example for Postal, [here](https://github.com/Wouter0100/freescout-postal/).

It would also be possible to use this for example for AWS SES Incoming emails and other e-mail providers providing incoming e-mail abilities.

No behaviour changed by default.

https://user-images.githubusercontent.com/864520/146613993-d801d2d6-bb89-4205-912e-f6cc17c4e205.mp4

### CODE REVIEW

**Comment by Wouter0100** [comment]
Thinking about it, this still needs some work for the default FetchEmails command to skip the non-default protocols, so please don't merge yet as I will attempt to add that as soon as possible.

Regardless, I'm still thinking about your opinion on this and like to know if this is something that would be able to get merged at some point.

**Comment by Wouter0100** [comment]
I haven't had time for the above. I'm still planning on doing that ASAP, as we need it ourselves as well :).

Regardless, as you've most likely seen as well - ideally we would move the handling of e-mails in the FetchEmails to a more accessible location for other scripts/modules to be able to process e-mails. But, without it the proposed solution should work just fine.

**Comment by Wouter0100** [comment]
Implemented a fix for that as well, see [here](https://github.com/freescout-helpdesk/freescout/pull/1593/files#diff-e12b566d766fcc92a657c5895fa11b550afb364c47c64512ee5bbe9a5f639666R78-R79).

**Comment by Wouter0100** [comment]
We deployed in production now. Got a mix of Mailboxes working perfectly fine.

**Comment by freescout-helpdesk** [comment]
Some changes are needed:

1) Replace `@foreach($mailbox->getInProtocols() as $key => $name)` with @action()

2) `div` with default settings must be visible by default without need to show it via JS.
 
3) This `$this->mailboxes = Mailbox::whereIn('in_protocol', array_keys(Mailbox::$in_protocols))->get();` should be executed only if there are extra protocols in `Mailbox::getInProtocolDisplayNames()`;

4) `$response = \Eventy::filter('mailbox.fetch_test', $response, $mailbox);` - this filter should set $response['tested'], if this flag is set default checks should be skipped.

**Comment by Wouter0100** [comment]
I have added 2, 3 and 4. I however don't really understand what you mean with 1. As far as I know, @action is not a replacement for a foreach statement. And besides that, @action is not returning data?

Thanks for the feedback though.

**Comment by freescout-helpdesk** [comment]
See for example this: https://github.com/freescout-helpdesk/freescout/blob/c4a4f33633ef06ec8c9fc5cb668bb75cce2c7793/resources/views/conversations/view.blade.php#L152

**Comment by Wouter0100** [comment]
Hmm, I see. In that case you want us to manually do that logic? 

I've changed it. Could you please verify this is as you suggested?

**Comment by freescout-helpdesk** [comment]
If you wish feel free to share your custom module with others: https://github.com/freescout-helpdesk/freescout/wiki/Community-Modules

**Pull request merged**
