### PR TITLE
Allow to get module image from module.json

### PR DESCRIPTION
**Pull request by andrewlimaza**
Supports 'img' attribute for custom modules to pull from modules.json.

Add `"img": "path-to-image",`

### CODE REVIEW

**Comment by andrewlimaza** [comment]
Issue reference: https://github.com/freescout-helpdesk/freescout/issues/1526

**Comment by freescout-helpdesk** [comment]
PRs should be sent to master. What can be passed in the `img` parameter?

**Comment by andrewlimaza** [comment]
The parameter would be the path to the image. Such as `https://mywebsite/my-upload/my-image.png` for example. I can redo the PR to post this against master.

**Comment by andrewlimaza** [comment]
I redid the PR, my custom branch was being weird - https://github.com/freescout-helpdesk/freescout/pull/1528

**Pull request closed without merging**
